cp -r /home/mfrw/mariner-org/parity/SPECS/abattis-cantarell-fonts .
cp -r /home/mfrw/mariner-org/parity/SPECS/adcli .
cp -r /home/mfrw/mariner-org/parity/SPECS/advancecomp .
cp -r /home/mfrw/mariner-org/parity/SPECS/alsa-firmware .
cp -r /home/mfrw/mariner-org/parity/SPECS/alsa-plugins .
cp -r /home/mfrw/mariner-org/parity/SPECS/ant-antlr .
cp -r /home/mfrw/mariner-org/parity/SPECS/ant-antunit .
cp -r /home/mfrw/mariner-org/parity/SPECS/apache-commons-beanutils .
cp -r /home/mfrw/mariner-org/parity/SPECS/apache-commons-configuration .
cp -r /home/mfrw/mariner-org/parity/SPECS/apache-commons-dbcp .
cp -r /home/mfrw/mariner-org/parity/SPECS/apache-commons-digester .
cp -r /home/mfrw/mariner-org/parity/SPECS/apache-commons-exec .
cp -r /home/mfrw/mariner-org/parity/SPECS/apache-commons-jexl .
cp -r /home/mfrw/mariner-org/parity/SPECS/apache-commons-jxpath .
cp -r /home/mfrw/mariner-org/parity/SPECS/apache-commons-parent .
cp -r /home/mfrw/mariner-org/parity/SPECS/apache-commons-pool .
cp -r /home/mfrw/mariner-org/parity/SPECS/apache-commons-pool2 .
cp -r /home/mfrw/mariner-org/parity/SPECS/apache-commons-validator .
cp -r /home/mfrw/mariner-org/parity/SPECS/apache-commons-vfs .
cp -r /home/mfrw/mariner-org/parity/SPECS/apache-commons-vfs2 .
cp -r /home/mfrw/mariner-org/parity/SPECS/apache-ivy .
cp -r /home/mfrw/mariner-org/parity/SPECS/apache-rat .
cp -r /home/mfrw/mariner-org/parity/SPECS/apache-resource-bundles .
cp -r /home/mfrw/mariner-org/parity/SPECS/apiguardian .
cp -r /home/mfrw/mariner-org/parity/SPECS/appstream .
cp -r /home/mfrw/mariner-org/parity/SPECS/appstream-data .
cp -r /home/mfrw/mariner-org/parity/SPECS/assertj-core .
cp -r /home/mfrw/mariner-org/parity/SPECS/atkmm .
cp -r /home/mfrw/mariner-org/parity/SPECS/atlas .
cp -r /home/mfrw/mariner-org/parity/SPECS/avalon-logkit .
cp -r /home/mfrw/mariner-org/parity/SPECS/baobab .
cp -r /home/mfrw/mariner-org/parity/SPECS/bnd-maven-plugin .
cp -r /home/mfrw/mariner-org/parity/SPECS/bolt .
cp -r /home/mfrw/mariner-org/parity/SPECS/booth .
cp -r /home/mfrw/mariner-org/parity/SPECS/bouncycastle .
cp -r /home/mfrw/mariner-org/parity/SPECS/brltty .
cp -r /home/mfrw/mariner-org/parity/SPECS/bsf .
cp -r /home/mfrw/mariner-org/parity/SPECS/bsh .
cp -r /home/mfrw/mariner-org/parity/SPECS/bsh2 .
cp -r /home/mfrw/mariner-org/parity/SPECS/byte-buddy .
cp -r /home/mfrw/mariner-org/parity/SPECS/cairomm .
cp -r /home/mfrw/mariner-org/parity/SPECS/cdi-api .
cp -r /home/mfrw/mariner-org/parity/SPECS/cdparanoia .
cp -r /home/mfrw/mariner-org/parity/SPECS/cdrdao .
cp -r /home/mfrw/mariner-org/parity/SPECS/clufter .
cp -r /home/mfrw/mariner-org/parity/SPECS/clutter .
cp -r /home/mfrw/mariner-org/parity/SPECS/clutter-gst3 .
cp -r /home/mfrw/mariner-org/parity/SPECS/clutter-gtk .
cp -r /home/mfrw/mariner-org/parity/SPECS/codemodel .
cp -r /home/mfrw/mariner-org/parity/SPECS/cogl .
cp -r /home/mfrw/mariner-org/parity/SPECS/community-mysql .
cp -r /home/mfrw/mariner-org/parity/SPECS/cpptest .
cp -r /home/mfrw/mariner-org/parity/SPECS/crypto-policies .
cp -r /home/mfrw/mariner-org/parity/SPECS/disruptor .
cp -r /home/mfrw/mariner-org/parity/SPECS/dleyna-connector-dbus .
cp -r /home/mfrw/mariner-org/parity/SPECS/dleyna-core .
cp -r /home/mfrw/mariner-org/parity/SPECS/dleyna-renderer .
cp -r /home/mfrw/mariner-org/parity/SPECS/dleyna-server .
cp -r /home/mfrw/mariner-org/parity/SPECS/dlm .
cp -r /home/mfrw/mariner-org/parity/SPECS/dom4j .
cp -r /home/mfrw/mariner-org/parity/SPECS/dvgrab .
cp -r /home/mfrw/mariner-org/parity/SPECS/easymock .
cp -r /home/mfrw/mariner-org/parity/SPECS/elinks .
cp -r /home/mfrw/mariner-org/parity/SPECS/esc .
cp -r /home/mfrw/mariner-org/parity/SPECS/exec-maven-plugin .
cp -r /home/mfrw/mariner-org/parity/SPECS/farstream02 .
cp -r /home/mfrw/mariner-org/parity/SPECS/fasterxml-oss-parent .
cp -r /home/mfrw/mariner-org/parity/SPECS/felix-osgi-obr .
cp -r /home/mfrw/mariner-org/parity/SPECS/felix-parent .
cp -r /home/mfrw/mariner-org/parity/SPECS/felix-utils .
cp -r /home/mfrw/mariner-org/parity/SPECS/fence-agents .
cp -r /home/mfrw/mariner-org/parity/SPECS/fftw .
cp -r /home/mfrw/mariner-org/parity/SPECS/flatpak .
cp -r /home/mfrw/mariner-org/parity/SPECS/flatpak-builder .
cp -r /home/mfrw/mariner-org/parity/SPECS/fluidsynth .
cp -r /home/mfrw/mariner-org/parity/SPECS/flute .
cp -r /home/mfrw/mariner-org/parity/SPECS/foomatic .
cp -r /home/mfrw/mariner-org/parity/SPECS/foomatic-db .
cp -r /home/mfrw/mariner-org/parity/SPECS/fprintd .
cp -r /home/mfrw/mariner-org/parity/SPECS/freerdp .
cp -r /home/mfrw/mariner-org/parity/SPECS/frr .
cp -r /home/mfrw/mariner-org/parity/SPECS/fusesource-pom .
cp -r /home/mfrw/mariner-org/parity/SPECS/gavl .
cp -r /home/mfrw/mariner-org/parity/SPECS/gdisk .
cp -r /home/mfrw/mariner-org/parity/SPECS/gdm .
cp -r /home/mfrw/mariner-org/parity/SPECS/geoclue2 .
cp -r /home/mfrw/mariner-org/parity/SPECS/geocode-glib .
cp -r /home/mfrw/mariner-org/parity/SPECS/geronimo-annotation .
cp -r /home/mfrw/mariner-org/parity/SPECS/geronimo-jaxrpc .
cp -r /home/mfrw/mariner-org/parity/SPECS/geronimo-jms .
cp -r /home/mfrw/mariner-org/parity/SPECS/geronimo-jta .
cp -r /home/mfrw/mariner-org/parity/SPECS/geronimo-osgi-support .
cp -r /home/mfrw/mariner-org/parity/SPECS/geronimo-parent-poms .
cp -r /home/mfrw/mariner-org/parity/SPECS/geronimo-saaj .
cp -r /home/mfrw/mariner-org/parity/SPECS/geronimo-specs-pom .
cp -r /home/mfrw/mariner-org/parity/SPECS/ghostscript .
cp -r /home/mfrw/mariner-org/parity/SPECS/glassfish-dtd-parser .
cp -r /home/mfrw/mariner-org/parity/SPECS/glassfish-el .
cp -r /home/mfrw/mariner-org/parity/SPECS/glassfish-fastinfoset .
cp -r /home/mfrw/mariner-org/parity/SPECS/glassfish-hk2 .
cp -r /home/mfrw/mariner-org/parity/SPECS/glassfish-jaxb .
cp -r /home/mfrw/mariner-org/parity/SPECS/glassfish-jaxb-api .
cp -r /home/mfrw/mariner-org/parity/SPECS/glassfish-jax-rs-api .
cp -r /home/mfrw/mariner-org/parity/SPECS/glassfish-jsp .
cp -r /home/mfrw/mariner-org/parity/SPECS/glassfish-jsp-api .
cp -r /home/mfrw/mariner-org/parity/SPECS/glog .
cp -r /home/mfrw/mariner-org/parity/SPECS/gnome-session .
cp -r /home/mfrw/mariner-org/parity/SPECS/gnome-settings-daemon .
cp -r /home/mfrw/mariner-org/parity/SPECS/gnome-shell .
cp -r /home/mfrw/mariner-org/parity/SPECS/google-api-python-client .
cp -r /home/mfrw/mariner-org/parity/SPECS/google-gson .
cp -r /home/mfrw/mariner-org/parity/SPECS/google-guice .
cp -r /home/mfrw/mariner-org/parity/SPECS/gsound .
cp -r /home/mfrw/mariner-org/parity/SPECS/gssdp .
cp -r /home/mfrw/mariner-org/parity/SPECS/gstreamer1-plugins-bad-free .
cp -r /home/mfrw/mariner-org/parity/SPECS/gstreamer1-plugins-base .
cp -r /home/mfrw/mariner-org/parity/SPECS/gstreamer1-plugins-good .
cp -r /home/mfrw/mariner-org/parity/SPECS/gtkmm30 .
cp -r /home/mfrw/mariner-org/parity/SPECS/gtksourceview4 .
cp -r /home/mfrw/mariner-org/parity/SPECS/gtk-vnc .
cp -r /home/mfrw/mariner-org/parity/SPECS/gucharmap .
cp -r /home/mfrw/mariner-org/parity/SPECS/gupnp .
cp -r /home/mfrw/mariner-org/parity/SPECS/gupnp-dlna .
cp -r /home/mfrw/mariner-org/parity/SPECS/gupnp-igd .
cp -r /home/mfrw/mariner-org/parity/SPECS/HdrHistogram .
cp -r /home/mfrw/mariner-org/parity/SPECS/hfsplus-tools .
cp -r /home/mfrw/mariner-org/parity/SPECS/hsqldb .
cp -r /home/mfrw/mariner-org/parity/SPECS/httpcomponents-project .
cp -r /home/mfrw/mariner-org/parity/SPECS/hunspell-ak .
cp -r /home/mfrw/mariner-org/parity/SPECS/hunspell-am .
cp -r /home/mfrw/mariner-org/parity/SPECS/hunspell-ber .
cp -r /home/mfrw/mariner-org/parity/SPECS/hunspell-lt .
cp -r /home/mfrw/mariner-org/parity/SPECS/hunspell-oc .
cp -r /home/mfrw/mariner-org/parity/SPECS/hunspell-ss .
cp -r /home/mfrw/mariner-org/parity/SPECS/hunspell-st .
cp -r /home/mfrw/mariner-org/parity/SPECS/hunspell-ti .
cp -r /home/mfrw/mariner-org/parity/SPECS/hunspell-ur .
cp -r /home/mfrw/mariner-org/parity/SPECS/hunspell-zu .
cp -r /home/mfrw/mariner-org/parity/SPECS/hyphen-cy .
cp -r /home/mfrw/mariner-org/parity/SPECS/hyphen-eu .
cp -r /home/mfrw/mariner-org/parity/SPECS/ibus-libpinyin .
cp -r /home/mfrw/mariner-org/parity/SPECS/ibus-m17n .
cp -r /home/mfrw/mariner-org/parity/SPECS/idm-console-framework .
cp -r /home/mfrw/mariner-org/parity/SPECS/igt-gpu-tools .
cp -r /home/mfrw/mariner-org/parity/SPECS/imake .
cp -r /home/mfrw/mariner-org/parity/SPECS/ipa-gothic-fonts .
cp -r /home/mfrw/mariner-org/parity/SPECS/istack-commons .
cp -r /home/mfrw/mariner-org/parity/SPECS/iwd .
cp -r /home/mfrw/mariner-org/parity/SPECS/jack-audio-connection-kit .
cp -r /home/mfrw/mariner-org/parity/SPECS/jackson-annotations .
cp -r /home/mfrw/mariner-org/parity/SPECS/jackson-bom .
cp -r /home/mfrw/mariner-org/parity/SPECS/jackson-core .
cp -r /home/mfrw/mariner-org/parity/SPECS/jackson-databind .
cp -r /home/mfrw/mariner-org/parity/SPECS/jackson-jaxrs-providers .
cp -r /home/mfrw/mariner-org/parity/SPECS/jackson-modules-base .
cp -r /home/mfrw/mariner-org/parity/SPECS/jackson-parent .
cp -r /home/mfrw/mariner-org/parity/SPECS/jaf .
cp -r /home/mfrw/mariner-org/parity/SPECS/jakarta-commons-httpclient .
cp -r /home/mfrw/mariner-org/parity/SPECS/jakarta-oro .
cp -r /home/mfrw/mariner-org/parity/SPECS/jansi .
cp -r /home/mfrw/mariner-org/parity/SPECS/java-atk-wrapper .
cp -r /home/mfrw/mariner-org/parity/SPECS/javacc-maven-plugin .
cp -r /home/mfrw/mariner-org/parity/SPECS/javamail .
cp -r /home/mfrw/mariner-org/parity/SPECS/javaparser .
cp -r /home/mfrw/mariner-org/parity/SPECS/jbig2dec .
cp -r /home/mfrw/mariner-org/parity/SPECS/jboss-annotations-1.2-api .
cp -r /home/mfrw/mariner-org/parity/SPECS/jboss-el-2.2-api .
cp -r /home/mfrw/mariner-org/parity/SPECS/jboss-jaxrs-2.0-api .
cp -r /home/mfrw/mariner-org/parity/SPECS/jboss-jsp-2.2-api .
cp -r /home/mfrw/mariner-org/parity/SPECS/jboss-logging .
cp -r /home/mfrw/mariner-org/parity/SPECS/jboss-logging-tools .
cp -r /home/mfrw/mariner-org/parity/SPECS/jboss-logmanager .
cp -r /home/mfrw/mariner-org/parity/SPECS/jboss-modules .
cp -r /home/mfrw/mariner-org/parity/SPECS/jboss-parent .
cp -r /home/mfrw/mariner-org/parity/SPECS/jboss-servlet-3.0-api .
cp -r /home/mfrw/mariner-org/parity/SPECS/jctools .
cp -r /home/mfrw/mariner-org/parity/SPECS/jdeparser .
cp -r /home/mfrw/mariner-org/parity/SPECS/jdependency .
cp -r /home/mfrw/mariner-org/parity/SPECS/jdom .
cp -r /home/mfrw/mariner-org/parity/SPECS/jetty .
cp -r /home/mfrw/mariner-org/parity/SPECS/jetty-build-support .
cp -r /home/mfrw/mariner-org/parity/SPECS/jetty-parent .
cp -r /home/mfrw/mariner-org/parity/SPECS/jetty-toolchain .
cp -r /home/mfrw/mariner-org/parity/SPECS/jing-trang .
cp -r /home/mfrw/mariner-org/parity/SPECS/jline .
cp -r /home/mfrw/mariner-org/parity/SPECS/joda-convert .
cp -r /home/mfrw/mariner-org/parity/SPECS/joda-time .
cp -r /home/mfrw/mariner-org/parity/SPECS/jolokia-jvm-agent .
cp -r /home/mfrw/mariner-org/parity/SPECS/json_simple .
cp -r /home/mfrw/mariner-org/parity/SPECS/jsr-311 .
cp -r /home/mfrw/mariner-org/parity/SPECS/jss .
cp -r /home/mfrw/mariner-org/parity/SPECS/junit5 .
cp -r /home/mfrw/mariner-org/parity/SPECS/jvnet-parent .
cp -r /home/mfrw/mariner-org/parity/SPECS/kxml .
cp -r /home/mfrw/mariner-org/parity/SPECS/ldapjdk .
cp -r /home/mfrw/mariner-org/parity/SPECS/lensfun .
cp -r /home/mfrw/mariner-org/parity/SPECS/libao .
cp -r /home/mfrw/mariner-org/parity/SPECS/libappindicator .
cp -r /home/mfrw/mariner-org/parity/SPECS/libappstream-glib .
cp -r /home/mfrw/mariner-org/parity/SPECS/libblockdev .
cp -r /home/mfrw/mariner-org/parity/SPECS/libcanberra .
cp -r /home/mfrw/mariner-org/parity/SPECS/libchamplain .
cp -r /home/mfrw/mariner-org/parity/SPECS/libcmpiutil .
cp -r /home/mfrw/mariner-org/parity/SPECS/libcroco .
cp -r /home/mfrw/mariner-org/parity/SPECS/libdmapsharing .
cp -r /home/mfrw/mariner-org/parity/SPECS/libdv .
cp -r /home/mfrw/mariner-org/parity/SPECS/libfprint .
cp -r /home/mfrw/mariner-org/parity/SPECS/libgdither .
cp -r /home/mfrw/mariner-org/parity/SPECS/libgovirt .
cp -r /home/mfrw/mariner-org/parity/SPECS/libidn .
cp -r /home/mfrw/mariner-org/parity/SPECS/libijs .
cp -r /home/mfrw/mariner-org/parity/SPECS/libindicator .
cp -r /home/mfrw/mariner-org/parity/SPECS/liblouis .
cp -r /home/mfrw/mariner-org/parity/SPECS/libmemcached .
cp -r /home/mfrw/mariner-org/parity/SPECS/libmikmod .
cp -r /home/mfrw/mariner-org/parity/SPECS/libnice .
cp -r /home/mfrw/mariner-org/parity/SPECS/libofa .
cp -r /home/mfrw/mariner-org/parity/SPECS/liboggz .
cp -r /home/mfrw/mariner-org/parity/SPECS/libomxil-bellagio .
cp -r /home/mfrw/mariner-org/parity/SPECS/libosinfo .
cp -r /home/mfrw/mariner-org/parity/SPECS/libpng12 .
cp -r /home/mfrw/mariner-org/parity/SPECS/libpng15 .
cp -r /home/mfrw/mariner-org/parity/SPECS/libpq .
cp -r /home/mfrw/mariner-org/parity/SPECS/libreport .
cp -r /home/mfrw/mariner-org/parity/SPECS/libsamplerate .
cp -r /home/mfrw/mariner-org/parity/SPECS/libshout .
cp -r /home/mfrw/mariner-org/parity/SPECS/libspectre .
cp -r /home/mfrw/mariner-org/parity/SPECS/libtheora .
cp -r /home/mfrw/mariner-org/parity/SPECS/libtimezonemap .
cp -r /home/mfrw/mariner-org/parity/SPECS/libucil .
cp -r /home/mfrw/mariner-org/parity/SPECS/libunicap .
cp -r /home/mfrw/mariner-org/parity/SPECS/libvncserver .
cp -r /home/mfrw/mariner-org/parity/SPECS/libwpd .
cp -r /home/mfrw/mariner-org/parity/SPECS/libwpg .
cp -r /home/mfrw/mariner-org/parity/SPECS/libxmlb .
cp -r /home/mfrw/mariner-org/parity/SPECS/libyang .
cp -r /home/mfrw/mariner-org/parity/SPECS/lilv .
cp -r /home/mfrw/mariner-org/parity/SPECS/linuxconsoletools .
cp -r /home/mfrw/mariner-org/parity/SPECS/Lmod .
cp -r /home/mfrw/mariner-org/parity/SPECS/log4j .
cp -r /home/mfrw/mariner-org/parity/SPECS/log4j12 .
cp -r /home/mfrw/mariner-org/parity/SPECS/lua-posix .
cp -r /home/mfrw/mariner-org/parity/SPECS/lv2 .
cp -r /home/mfrw/mariner-org/parity/SPECS/lxsession .
cp -r /home/mfrw/mariner-org/parity/SPECS/mariadb-java-client .
cp -r /home/mfrw/mariner-org/parity/SPECS/maven2 .
cp -r /home/mfrw/mariner-org/parity/SPECS/maven-antrun-plugin .
cp -r /home/mfrw/mariner-org/parity/SPECS/maven-archiver .
cp -r /home/mfrw/mariner-org/parity/SPECS/maven-artifact-resolver .
cp -r /home/mfrw/mariner-org/parity/SPECS/maven-artifact-transfer .
cp -r /home/mfrw/mariner-org/parity/SPECS/maven-assembly-plugin .
cp -r /home/mfrw/mariner-org/parity/SPECS/maven-clean-plugin .
cp -r /home/mfrw/mariner-org/parity/SPECS/maven-common-artifact-filters .
cp -r /home/mfrw/mariner-org/parity/SPECS/maven-compiler-plugin .
cp -r /home/mfrw/mariner-org/parity/SPECS/maven-dependency-analyzer .
cp -r /home/mfrw/mariner-org/parity/SPECS/maven-dependency-plugin .
cp -r /home/mfrw/mariner-org/parity/SPECS/maven-dependency-tree .
cp -r /home/mfrw/mariner-org/parity/SPECS/maven-doxia .
cp -r /home/mfrw/mariner-org/parity/SPECS/maven-doxia-sitetools .
cp -r /home/mfrw/mariner-org/parity/SPECS/maven-enforcer .
cp -r /home/mfrw/mariner-org/parity/SPECS/maven-file-management .
cp -r /home/mfrw/mariner-org/parity/SPECS/maven-filtering .
cp -r /home/mfrw/mariner-org/parity/SPECS/maven-install-plugin .
cp -r /home/mfrw/mariner-org/parity/SPECS/maven-invoker .
cp -r /home/mfrw/mariner-org/parity/SPECS/maven-invoker-plugin .
cp -r /home/mfrw/mariner-org/parity/SPECS/maven-jar-plugin .
cp -r /home/mfrw/mariner-org/parity/SPECS/maven-javadoc-plugin .
cp -r /home/mfrw/mariner-org/parity/SPECS/maven-osgi .
cp -r /home/mfrw/mariner-org/parity/SPECS/maven-plugin-build-helper .
cp -r /home/mfrw/mariner-org/parity/SPECS/maven-plugin-bundle .
cp -r /home/mfrw/mariner-org/parity/SPECS/maven-plugin-plugin .
cp -r /home/mfrw/mariner-org/parity/SPECS/maven-plugin-plugin-bootstrap .
cp -r /home/mfrw/mariner-org/parity/SPECS/maven-plugins-pom .
cp -r /home/mfrw/mariner-org/parity/SPECS/maven-plugin-testing .
cp -r /home/mfrw/mariner-org/parity/SPECS/maven-plugin-tools .
cp -r /home/mfrw/mariner-org/parity/SPECS/maven-remote-resources-plugin .
cp -r /home/mfrw/mariner-org/parity/SPECS/maven-replacer-plugin .
cp -r /home/mfrw/mariner-org/parity/SPECS/maven-reporting-api .
cp -r /home/mfrw/mariner-org/parity/SPECS/maven-reporting-impl .
cp -r /home/mfrw/mariner-org/parity/SPECS/maven-resolver .
cp -r /home/mfrw/mariner-org/parity/SPECS/maven-resources-plugin .
cp -r /home/mfrw/mariner-org/parity/SPECS/maven-script-interpreter .
cp -r /home/mfrw/mariner-org/parity/SPECS/maven-shade-plugin .
cp -r /home/mfrw/mariner-org/parity/SPECS/maven-shared .
cp -r /home/mfrw/mariner-org/parity/SPECS/maven-shared-incremental .
cp -r /home/mfrw/mariner-org/parity/SPECS/maven-shared-io .
cp -r /home/mfrw/mariner-org/parity/SPECS/maven-shared-utils .
cp -r /home/mfrw/mariner-org/parity/SPECS/maven-source-plugin .
cp -r /home/mfrw/mariner-org/parity/SPECS/maven-surefire .
cp -r /home/mfrw/mariner-org/parity/SPECS/maven-surefire-plugins .
cp -r /home/mfrw/mariner-org/parity/SPECS/maven-verifier .
cp -r /home/mfrw/mariner-org/parity/SPECS/maven-verifier-plugin .
cp -r /home/mfrw/mariner-org/parity/SPECS/maven-wagon .
cp -r /home/mfrw/mariner-org/parity/SPECS/mksh .
cp -r /home/mfrw/mariner-org/parity/SPECS/mockito .
cp -r /home/mfrw/mariner-org/parity/SPECS/modello .
cp -r /home/mfrw/mariner-org/parity/SPECS/modello-maven-plugin .
cp -r /home/mfrw/mariner-org/parity/SPECS/mod_nss .
cp -r /home/mfrw/mariner-org/parity/SPECS/mojo-parent .
cp -r /home/mfrw/mariner-org/parity/SPECS/mpg123 .
cp -r /home/mfrw/mariner-org/parity/SPECS/mpich .
cp -r /home/mfrw/mariner-org/parity/SPECS/msv .
cp -r /home/mfrw/mariner-org/parity/SPECS/munge-maven-plugin .
cp -r /home/mfrw/mariner-org/parity/SPECS/mysql-connector-java .
cp -r /home/mfrw/mariner-org/parity/SPECS/mysql-connector-odbc .
cp -r /home/mfrw/mariner-org/parity/SPECS/mythes-en .
cp -r /home/mfrw/mariner-org/parity/SPECS/mythes-it .
cp -r /home/mfrw/mariner-org/parity/SPECS/netsniff-ng .
cp -r /home/mfrw/mariner-org/parity/SPECS/nmstate .
cp -r /home/mfrw/mariner-org/parity/SPECS/ocaml-labltk .
cp -r /home/mfrw/mariner-org/parity/SPECS/ocaml-odoc .
cp -r /home/mfrw/mariner-org/parity/SPECS/ongres-scram .
cp -r /home/mfrw/mariner-org/parity/SPECS/opal .
cp -r /home/mfrw/mariner-org/parity/SPECS/openhpi .
cp -r /home/mfrw/mariner-org/parity/SPECS/openmpi .
cp -r /home/mfrw/mariner-org/parity/SPECS/openrdate .
cp -r /home/mfrw/mariner-org/parity/SPECS/opentest4j .
cp -r /home/mfrw/mariner-org/parity/SPECS/oprofile .
cp -r /home/mfrw/mariner-org/parity/SPECS/ORBit2 .
cp -r /home/mfrw/mariner-org/parity/SPECS/osinfo-db .
cp -r /home/mfrw/mariner-org/parity/SPECS/osinfo-db-tools .
cp -r /home/mfrw/mariner-org/parity/SPECS/pacemaker .
cp -r /home/mfrw/mariner-org/parity/SPECS/PackageKit .
cp -r /home/mfrw/mariner-org/parity/SPECS/pangomm .
cp -r /home/mfrw/mariner-org/parity/SPECS/pegdown .
cp -r /home/mfrw/mariner-org/parity/SPECS/perl-Alien-Libxml2 .
cp -r /home/mfrw/mariner-org/parity/SPECS/perl-Digest-BubbleBabble .
cp -r /home/mfrw/mariner-org/parity/SPECS/perl-Image-Info .
cp -r /home/mfrw/mariner-org/parity/SPECS/perl-libnet .
cp -r /home/mfrw/mariner-org/parity/SPECS/perl-Mail-DKIM .
cp -r /home/mfrw/mariner-org/parity/SPECS/perl-Mail-SPF .
cp -r /home/mfrw/mariner-org/parity/SPECS/perl-Module-Install-AutoLicense .
cp -r /home/mfrw/mariner-org/parity/SPECS/perl-Module-Install-ReadmeFromPod .
cp -r /home/mfrw/mariner-org/parity/SPECS/perl-Module-Package-Au .
cp -r /home/mfrw/mariner-org/parity/SPECS/perl-Net-DNS .
cp -r /home/mfrw/mariner-org/parity/SPECS/perl-Net-DNS-Resolver-Mock .
cp -r /home/mfrw/mariner-org/parity/SPECS/perl-Net-DNS-Resolver-Programmable .
cp -r /home/mfrw/mariner-org/parity/SPECS/perl-Pod-Escapes .
cp -r /home/mfrw/mariner-org/parity/SPECS/perl-Razor-Agent .
cp -r /home/mfrw/mariner-org/parity/SPECS/perl-Test-Harness .
cp -r /home/mfrw/mariner-org/parity/SPECS/perl-Test-Simple .
cp -r /home/mfrw/mariner-org/parity/SPECS/perl-Unicode-EastAsianWidth .
cp -r /home/mfrw/mariner-org/parity/SPECS/perl-XML-LibXSLT .
cp -r /home/mfrw/mariner-org/parity/SPECS/phodav .
cp -r /home/mfrw/mariner-org/parity/SPECS/php-fedora-autoloader .
cp -r /home/mfrw/mariner-org/parity/SPECS/pipewire .
cp -r /home/mfrw/mariner-org/parity/SPECS/pki-core .
cp -r /home/mfrw/mariner-org/parity/SPECS/plexus-ant-factory .
cp -r /home/mfrw/mariner-org/parity/SPECS/plexus-archiver .
cp -r /home/mfrw/mariner-org/parity/SPECS/plexus-bsh-factory .
cp -r /home/mfrw/mariner-org/parity/SPECS/plexus-build-api .
cp -r /home/mfrw/mariner-org/parity/SPECS/plexus-cipher .
cp -r /home/mfrw/mariner-org/parity/SPECS/plexus-cli .
cp -r /home/mfrw/mariner-org/parity/SPECS/plexus-compiler .
cp -r /home/mfrw/mariner-org/parity/SPECS/plexus-component-factories-pom .
cp -r /home/mfrw/mariner-org/parity/SPECS/plexus-component-metadata .
cp -r /home/mfrw/mariner-org/parity/SPECS/plexus-components-pom .
cp -r /home/mfrw/mariner-org/parity/SPECS/plexus-containers .
cp -r /home/mfrw/mariner-org/parity/SPECS/plexus-i18n .
cp -r /home/mfrw/mariner-org/parity/SPECS/plexus-interactivity .
cp -r /home/mfrw/mariner-org/parity/SPECS/plexus-languages .
cp -r /home/mfrw/mariner-org/parity/SPECS/plexus-metadata-generator .
cp -r /home/mfrw/mariner-org/parity/SPECS/plexus-resources .
cp -r /home/mfrw/mariner-org/parity/SPECS/plexus-sec-dispatcher .
cp -r /home/mfrw/mariner-org/parity/SPECS/plexus-velocity .
cp -r /home/mfrw/mariner-org/parity/SPECS/pngcrush .
cp -r /home/mfrw/mariner-org/parity/SPECS/pnm2ppa .
cp -r /home/mfrw/mariner-org/parity/SPECS/portaudio .
cp -r /home/mfrw/mariner-org/parity/SPECS/prometheus-jmx-exporter .
cp -r /home/mfrw/mariner-org/parity/SPECS/prometheus-simpleclient-java .
cp -r /home/mfrw/mariner-org/parity/SPECS/protobuf-java .
cp -r /home/mfrw/mariner-org/parity/SPECS/ptlib .
cp -r /home/mfrw/mariner-org/parity/SPECS/pulseaudio .
cp -r /home/mfrw/mariner-org/parity/SPECS/pygobject2 .
cp -r /home/mfrw/mariner-org/parity/SPECS/pykickstart .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-adal .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-amqp .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-beautifulsoup4 .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-billiard .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-case .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-celery .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-crypto .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-dbusmock .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-ddt .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-enchant .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-eventlet .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-factory-boy .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-fasteners .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-httplib2 .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-httpretty .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-invoke .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-jeepney .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-junitxml .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-keystoneauth1 .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-keystoneclient .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-lesscpy .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-lexicon .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-meh .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-memcached .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-minimock .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-mox3 .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-msal .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-msrest .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-msrestazure .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-ndg_httpsclient .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-novaclient .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-nss .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-oauth2client .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-ordered-set .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-oslo-config .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-oslo-i18n .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-oslo-serialization .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-oslotest .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-oslo-utils .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-paramiko .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-paste .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-pid .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-pytest-randomly .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-pytest-relaxed .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-rdflib .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-SecretStorage .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-setproctitle .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-spec .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-stestr .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-sure .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-sushy .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-testpath .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-vine .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-waitress .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-webtest .
cp -r /home/mfrw/mariner-org/parity/SPECS/python-yubico .
cp -r /home/mfrw/mariner-org/parity/SPECS/pyxdg .
cp -r /home/mfrw/mariner-org/parity/SPECS/qrencode .
cp -r /home/mfrw/mariner-org/parity/SPECS/rcs .
cp -r /home/mfrw/mariner-org/parity/SPECS/redfish-finder .
cp -r /home/mfrw/mariner-org/parity/SPECS/relaxngcc .
cp -r /home/mfrw/mariner-org/parity/SPECS/resteasy .
cp -r /home/mfrw/mariner-org/parity/SPECS/rubygem-abrt .
cp -r /home/mfrw/mariner-org/parity/SPECS/rubygem-bson .
cp -r /home/mfrw/mariner-org/parity/SPECS/rubygem-builder .
cp -r /home/mfrw/mariner-org/parity/SPECS/rubygem-diff-lcs .
cp -r /home/mfrw/mariner-org/parity/SPECS/rubygem-flexmock .
cp -r /home/mfrw/mariner-org/parity/SPECS/rubygem-maruku .
cp -r /home/mfrw/mariner-org/parity/SPECS/rubygem-method_source .
cp -r /home/mfrw/mariner-org/parity/SPECS/rubygem-mysql2 .
cp -r /home/mfrw/mariner-org/parity/SPECS/rubygem-pry .
cp -r /home/mfrw/mariner-org/parity/SPECS/rubygem-rdoc .
cp -r /home/mfrw/mariner-org/parity/SPECS/rubygem-rspec-expectations .
cp -r /home/mfrw/mariner-org/parity/SPECS/rubygem-rspec-mocks .
cp -r /home/mfrw/mariner-org/parity/SPECS/rubygem-rspec-support .
cp -r /home/mfrw/mariner-org/parity/SPECS/rubygem-thread_order .
cp -r /home/mfrw/mariner-org/parity/SPECS/sac .
cp -r /home/mfrw/mariner-org/parity/SPECS/sbd .
cp -r /home/mfrw/mariner-org/parity/SPECS/scannotation .
cp -r /home/mfrw/mariner-org/parity/SPECS/scipy .
cp -r /home/mfrw/mariner-org/parity/SPECS/scotch .
cp -r /home/mfrw/mariner-org/parity/SPECS/SDL .
cp -r /home/mfrw/mariner-org/parity/SPECS/SDL2 .
cp -r /home/mfrw/mariner-org/parity/SPECS/SDL_sound .
cp -r /home/mfrw/mariner-org/parity/SPECS/seahorse-sharing .
cp -r /home/mfrw/mariner-org/parity/SPECS/SFML .
cp -r /home/mfrw/mariner-org/parity/SPECS/shrinkwrap .
cp -r /home/mfrw/mariner-org/parity/SPECS/sisu .
cp -r /home/mfrw/mariner-org/parity/SPECS/slf4j-sources .
cp -r /home/mfrw/mariner-org/parity/SPECS/sonatype-oss-parent .
cp -r /home/mfrw/mariner-org/parity/SPECS/sos-collector .
cp -r /home/mfrw/mariner-org/parity/SPECS/sox .
cp -r /home/mfrw/mariner-org/parity/SPECS/spamassassin .
cp -r /home/mfrw/mariner-org/parity/SPECS/spec-version-maven-plugin .
cp -r /home/mfrw/mariner-org/parity/SPECS/spice .
cp -r /home/mfrw/mariner-org/parity/SPECS/squid .
cp -r /home/mfrw/mariner-org/parity/SPECS/sratom .
cp -r /home/mfrw/mariner-org/parity/SPECS/sssd .
cp -r /home/mfrw/mariner-org/parity/SPECS/stax2-api .
cp -r /home/mfrw/mariner-org/parity/SPECS/stax-ex .
cp -r /home/mfrw/mariner-org/parity/SPECS/stratisd .
cp -r /home/mfrw/mariner-org/parity/SPECS/subscription-manager .
cp -r /home/mfrw/mariner-org/parity/SPECS/suitesparse .
cp -r /home/mfrw/mariner-org/parity/SPECS/sysprof .
cp -r /home/mfrw/mariner-org/parity/SPECS/tagsoup .
cp -r /home/mfrw/mariner-org/parity/SPECS/tclx .
cp -r /home/mfrw/mariner-org/parity/SPECS/testng .
cp -r /home/mfrw/mariner-org/parity/SPECS/tix .
cp -r /home/mfrw/mariner-org/parity/SPECS/tog-pegasus .
cp -r /home/mfrw/mariner-org/parity/SPECS/tomcat .
cp -r /home/mfrw/mariner-org/parity/SPECS/tomcatjss .
cp -r /home/mfrw/mariner-org/parity/SPECS/tomcat-taglibs-parent .
cp -r /home/mfrw/mariner-org/parity/SPECS/tomcat-taglibs-standard .
cp -r /home/mfrw/mariner-org/parity/SPECS/torque .
cp -r /home/mfrw/mariner-org/parity/SPECS/tpm2-abrmd-selinux .
cp -r /home/mfrw/mariner-org/parity/SPECS/transfig .
cp -r /home/mfrw/mariner-org/parity/SPECS/udisks2 .
cp -r /home/mfrw/mariner-org/parity/SPECS/uhttpmock .
cp -r /home/mfrw/mariner-org/parity/SPECS/umockdev .
cp -r /home/mfrw/mariner-org/parity/SPECS/univocity-parsers .
cp -r /home/mfrw/mariner-org/parity/SPECS/urw-base35-fonts .
cp -r /home/mfrw/mariner-org/parity/SPECS/velocity .
cp -r /home/mfrw/mariner-org/parity/SPECS/virt-manager .
cp -r /home/mfrw/mariner-org/parity/SPECS/virt-v2v .
cp -r /home/mfrw/mariner-org/parity/SPECS/vorbis-tools .
cp -r /home/mfrw/mariner-org/parity/SPECS/weld-parent .
cp -r /home/mfrw/mariner-org/parity/SPECS/werken-xpath .
cp -r /home/mfrw/mariner-org/parity/SPECS/woodstox-core .
cp -r /home/mfrw/mariner-org/parity/SPECS/wordnet .
cp -r /home/mfrw/mariner-org/parity/SPECS/ws-commons-util .
cp -r /home/mfrw/mariner-org/parity/SPECS/wsdl4j .
cp -r /home/mfrw/mariner-org/parity/SPECS/ws-jaxme .
cp -r /home/mfrw/mariner-org/parity/SPECS/xapian-core .
cp -r /home/mfrw/mariner-org/parity/SPECS/xmlrpc .
cp -r /home/mfrw/mariner-org/parity/SPECS/xmlrpc-c .
cp -r /home/mfrw/mariner-org/parity/SPECS/xmlstreambuffer .
cp -r /home/mfrw/mariner-org/parity/SPECS/xmvn .
cp -r /home/mfrw/mariner-org/parity/SPECS/xmvn-connector-aether .
cp -r /home/mfrw/mariner-org/parity/SPECS/xmvn-connector-ivy .
cp -r /home/mfrw/mariner-org/parity/SPECS/xmvn-mojo .
cp -r /home/mfrw/mariner-org/parity/SPECS/xmvn-tools .
cp -r /home/mfrw/mariner-org/parity/SPECS/xsom .
cp -r /home/mfrw/mariner-org/parity/SPECS/xstream .
cp -r /home/mfrw/mariner-org/parity/SPECS/zziplib .
